import os
import requests
from dotenv import load_dotenv
from app.utils import logger

load_dotenv()

NOTION_API_KEY = os.getenv("NOTION_API_KEY")
HEADERS = {
    "Authorization": f"Bearer {NOTION_API_KEY}",
    "Content-Type": "application/json",
    "Notion-Version": "2022-06-28"
}

def fetch_products(database_id: str):
    """
    Fetch active products from Notion Database.
    This is a simplified version, should return a list of Product models.
    """
    url = f"https://api.notion.com/v1/databases/{database_id}/query"
    try:
        response = requests.post(url, headers=HEADERS, json={})
        response.raise_for_status()
        data = response.json()
        logger.info(f"Fetched {len(data.get('results', []))} products from Notion.")
        return data.get('results', [])
    except Exception as e:
        logger.error(f"Error fetching products: {e}")
        return []

def insert_post(database_id: str, post_data: dict, children: list = None):
    """
    Insert a new draft post generated by Content Agent.
    """
    url = "https://api.notion.com/v1/pages"
    payload = {
        "parent": {"database_id": database_id},
        "properties": post_data # Map to Notion properties structure
    }
    if children is not None:
        payload["children"] = children
    logger.info("recode post data: " + str(payload));
    try:
        response = requests.post(url, headers=HEADERS, json=payload)
        response.raise_for_status()
        logger.info("Successfully inserted new post into Notion.")
        return response.json()
    except requests.exceptions.HTTPError as e:
        logger.error(f"Error inserting post: {e}. Details: {e.response.text}")
        return None
    except Exception as e:
        logger.error(f"Error inserting post: {e}")
        return None
        
# Các hàm khác tương tự: fetch_orders, update_order_status
